# Generated by Django 4.1.3 on 2022-12-03 00:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(null=True)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
                ('image', models.ImageField(default='products/default.jpg', upload_to='upload_to')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='xwater.category')),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
    ]
