# Generated by Django 4.1.7 on 2023-04-29 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0009_alter_customuser_user_permissions'),
        ('products_api', '0005_remove_product_user_wishlist_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_api.adminprofile'),
            preserve_default=False,
        ),
    ]
