# Generated by Django 4.1.7 on 2023-05-02 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0009_alter_customuser_user_permissions'),
        ('products_api', '0007_rename_company_product_admincompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='admincompany',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, to='user_api.adminprofile'),
        ),
    ]
