# Generated by Django 4.1.7 on 2023-05-12 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products_api', '0009_alter_product_admincompany'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='user_wishlist',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user_wishlist',
            field=models.ForeignKey(blank=True, default=14, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
