# Generated by Django 4.1.7 on 2023-05-12 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_api', '0011_product_qnt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='qnt',
        ),
    ]
