# Generated by Django 4.1.7 on 2023-05-18 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products_api', '0012_remove_product_qnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='user_product', to='products_api.product'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user_wishlist',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_wish', to=settings.AUTH_USER_MODEL),
        ),
    ]
