# Generated by Django 4.1.7 on 2023-04-29 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0002_order_delivery_date_order_items_order_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 2, 17, 25, 52, 567692)),
        ),
    ]
