# Generated by Django 4.1.7 on 2023-05-13 00:23

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order_api', '0002_order_cart_alter_cart_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='delivery_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 16, 3, 23, 3, 407481)),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('cart', 'user')},
        ),
    ]
