# Generated by Django 4.1.7 on 2023-05-13 00:50

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0006_remove_order_cart_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery_date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 16, 3, 50, 12, 160344))),
                ('order_item', models.ManyToManyField(blank=True, to='order_api.order')),
            ],
        ),
    ]
