# Generated by Django 4.1.7 on 2023-05-13 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0009_remove_cart_order_item_order_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='delivery_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 16, 5, 0, 3, 144891)),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('cart', 'id')},
        ),
    ]
