# Generated by Django 4.1.7 on 2023-05-13 02:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0010_alter_cart_delivery_date_alter_order_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cart',
            name='order_item',
            field=models.ManyToManyField(blank=True, to='order_api.order'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='delivery_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 16, 5, 41, 20, 727415)),
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
    ]
