# Generated by Django 4.1.7 on 2023-05-18 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0012_alter_cart_delivery_date_alter_cart_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='delivery_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 21, 19, 28, 26, 238388)),
        ),
    ]
