# Generated by Django 4.1.7 on 2023-05-18 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0017_alter_cart_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='delivery_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 21, 20, 22, 44, 193029)),
        ),
    ]
