# Generated by Django 4.1.7 on 2023-05-27 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0029_alter_cart_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.AlterField(
            model_name='cart',
            name='delivery_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 30, 20, 37, 34, 974823)),
        ),
        migrations.AlterField(
            model_name='order',
            name='qnt',
            field=models.IntegerField(default=0),
        ),
    ]
