# Generated by Django 4.1.7 on 2023-06-02 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0033_alter_cart_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shipping',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='cart',
            name='delivery_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 5, 17, 12, 34, 921685)),
        ),
    ]
