# Generated by Django 4.1.7 on 2023-06-15 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0035_locationmodel_monthmodel_yearmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='delivery_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 18, 23, 56, 48, 100090)),
        ),
    ]
