# Generated by Django 4.1.7 on 2023-06-15 21:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0036_alter_cart_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='delivery_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 19, 0, 13, 10, 46335)),
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250)),
                ('billingaddress', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=6)),
                ('cardholdername', models.CharField(max_length=250)),
                ('cvv', models.CharField(max_length=250)),
                ('cardnumber', models.CharField(max_length=3)),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='country_name', to='order_api.locationmodel')),
                ('month', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='month_name', to='order_api.monthmodel')),
                ('year', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='year_name', to='order_api.yearmodel')),
            ],
        ),
    ]
