# Generated by Django 4.1.7 on 2023-06-15 22:27

import datetime
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0037_alter_cart_delivery_date_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='delivery_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 19, 1, 27, 23, 752482)),
        ),
        migrations.CreateModel(
            name='OrderInvoice',
            fields=[
                ('shipping', models.IntegerField(default=10)),
                ('invoice_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.ManyToManyField(blank=True, related_name='orders', to='order_api.order')),
            ],
        ),
    ]
