# Generated by Django 4.1.7 on 2023-06-16 00:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0038_alter_cart_delivery_date_orderinvoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinvoice',
            name='order',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='country',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='month',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='year',
        ),
        migrations.AlterField(
            model_name='cart',
            name='delivery_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 19, 3, 55, 49, 309093)),
        ),
        migrations.DeleteModel(
            name='LocationModel',
        ),
        migrations.DeleteModel(
            name='MonthModel',
        ),
        migrations.DeleteModel(
            name='OrderInvoice',
        ),
        migrations.DeleteModel(
            name='payment',
        ),
        migrations.DeleteModel(
            name='YearModel',
        ),
    ]
