# Generated by Django 4.1.7 on 2023-06-16 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0041_alter_cart_delivery_date_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='delivery_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 19, 4, 8, 35, 309018)),
        ),
    ]
