# Generated by Django 4.1.7 on 2023-06-16 01:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0042_alter_cart_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cardholdername',
            field=models.CharField(default='Test Name', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='cardnumber',
            field=models.CharField(default=123, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='cvv',
            field=models.CharField(default=1234567890123456, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='delivery_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 19, 4, 8, 59, 57168)),
        ),
    ]
