# Generated by Django 4.1.7 on 2023-06-16 01:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0043_payment_cardholdername_payment_cardnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='delivery_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 19, 4, 21, 51, 333981)),
        ),
    ]
