# Generated by Django 4.1.7 on 2023-06-16 01:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0047_alter_cart_delivery_date_orderinvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='delivery_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 19, 4, 45, 8, 742392)),
        ),
        migrations.RemoveField(
            model_name='orderinvoice',
            name='order',
        ),
        migrations.AddField(
            model_name='orderinvoice',
            name='order',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order_api.order'),
            preserve_default=False,
        ),
    ]
