# Generated by Django 4.1.7 on 2023-06-16 02:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0048_alter_cart_delivery_date_remove_orderinvoice_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinvoice',
            name='order',
        ),
        migrations.AddField(
            model_name='orderinvoice',
            name='cart',
            field=models.ForeignKey(blank=True, default=12, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='order_api.cart'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='delivery_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 19, 5, 45, 4, 621741)),
        ),
    ]
