# Generated by Django 4.1.7 on 2023-06-21 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0049_remove_orderinvoice_order_orderinvoice_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='delivery_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 24, 20, 9, 34, 660476)),
        ),
    ]
