# Generated by Django 4.1.7 on 2023-06-21 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0051_alter_cart_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='delivery_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 24, 23, 20, 36, 547305)),
        ),
    ]
