# Generated by Django 4.1.7 on 2023-04-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MlFarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rSC', models.FloatField()),
                ('pI', models.FloatField()),
                ('kr', models.FloatField()),
                ('mH', models.FloatField()),
                ('na', models.FloatField()),
                ('sAR', models.FloatField()),
                ('sSP', models.FloatField()),
                ('eC', models.IntegerField()),
                ('iWQI', models.IntegerField()),
                ('USABLE', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MlHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pH', models.FloatField()),
                ('sodium', models.FloatField()),
                ('magnesium', models.FloatField()),
                ('calcium', models.FloatField()),
                ('chloride', models.FloatField()),
                ('potassium', models.FloatField()),
                ('carbonate', models.FloatField()),
                ('sulphate', models.FloatField()),
                ('eC', models.IntegerField()),
                ('tH', models.IntegerField()),
                ('wQI', models.FloatField()),
                ('Potability', models.BooleanField()),
            ],
        ),
    ]
