# Generated by Django 4.1.7 on 2023-06-21 20:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_api', '0020_device'),
        ('ml_api', '0002_delete_mlfarm_delete_mlhome'),
    ]

    operations = [
        migrations.CreateModel(
            name='MlHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField()),
                ('tds', models.FloatField()),
                ('pH', models.FloatField()),
                ('sodium', models.FloatField()),
                ('magnesium', models.FloatField()),
                ('calcium', models.FloatField()),
                ('chloride', models.FloatField()),
                ('potassium', models.FloatField()),
                ('carbonate', models.FloatField()),
                ('sulphate', models.FloatField()),
                ('eC', models.IntegerField()),
                ('tH', models.IntegerField()),
                ('wQI', models.FloatField()),
                ('Potability', models.BooleanField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('device_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_api.device')),
            ],
        ),
        migrations.CreateModel(
            name='MlFarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField()),
                ('tds', models.FloatField()),
                ('rSC', models.FloatField()),
                ('pI', models.FloatField()),
                ('kr', models.FloatField()),
                ('mH', models.FloatField()),
                ('na', models.FloatField()),
                ('sAR', models.FloatField()),
                ('sSP', models.FloatField()),
                ('eC', models.IntegerField()),
                ('iWQI', models.IntegerField()),
                ('USABLE', models.BooleanField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('device_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_api.device')),
            ],
        ),
    ]
