# Generated by Django 4.1.7 on 2023-04-14 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0005_remove_customuser_is_suffer_heart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
    ]
