# Generated by Django 4.1.7 on 2023-05-18 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0011_customuser_social_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='social_account',
        ),
    ]
