# Generated by Django 4.1.7 on 2023-05-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0017_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(default='upload_to/default.jpg', upload_to='upload_to'),
        ),
    ]
