# Generated by Django 4.1.7 on 2023-06-21 17:09

from django.db import migrations, models
import user_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0018_alter_customuser_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[user_api.models.validate_phone_number]),
        ),
    ]
